class Util {
  static List<String> dailyChallenges = [
    'Reduce plastic waste: Carry a reusable water bottle and shopping bag.',
    'Compost food scraps: Start a small compost bin at home.',
    'Recycle properly: Learn local recycling guidelines and sort waste accordingly.',
    'Avoid single-use items: Opt for reusable alternatives like straws, cutlery, and coffee cups.',
    'Donate unwanted items: Give away clothes, furniture, or electronics to local charities.',
    'Unplug electronics: Turn off devices when not in use to save energy.',
    'Use energy-efficient appliances: Replace old appliances with energy-efficient models.',
    'Conserve water: Take shorter showers, fix leaky faucets, and water plants efficiently.',
    'Reduce air conditioning usage: Use fans or natural ventilation whenever possible.',
    'Switch to renewable energy: Explore options for solar or wind power if feasible.',
    'Walk or bike: Use active transportation for short trips to reduce carbon emissions.',
    'Carpool: Share rides with friends or colleagues to reduce traffic congestion.',
    'Use public transportation: Take buses or trains whenever possible.',
    'Support sustainable transportation initiatives: Advocate for better public transportation infrastructure.',
    'Reduce air travel: Consider alternative travel options or plan trips more efficiently.',
    'Buy local: Support local businesses and reduce the environmental impact of transportation.',
    'Choose sustainable products: Look for products made from recycled or eco-friendly materials.',
    'Reduce meat consumption: Opt for plant-based alternatives or reduce meat intake.',
    'Support fair trade: Choose products that are produced ethically and support fair labor practices.',
    'Avoid palm oil products: Contribute to the conservation of rainforests by avoiding palm oil.',
    'Volunteer: Give back to your community by volunteering for local organizations.',
    'Join a sustainability group: Connect with like-minded individuals and participate in community initiatives.',
    'Educate others: Share your knowledge of sustainability with friends, family, and colleagues.',
    'Participate in local events: Attend sustainability fairs, workshops, or conferences.',
    'Support local policies: Advocate for sustainable policies and initiatives in your community.',
    'Mindfulness and meditation: Practice mindfulness or meditation to reduce stress and promote well-being.',
    'Healthy eating: Choose nutritious foods and reduce consumption of processed foods.',
    'Regular exercise: Engage in physical activity to improve your health and well-being.',
    'Get enough sleep: Prioritize sleep to enhance your energy levels and focus.',
    'Spend time in nature: Connect with the natural world through activities like hiking, gardening, or simply enjoying outdoor spaces.'
  ];
}
